### ISSUE TITLE
npm run webpacker:dev doesn't update assets but :prod does

### ISSUE THREAD

**Issue by n0k5** [jimblue/grav-plugin-webpacker#10]
First of all, thanks for making this plugin, it's going to be really great if I can get it to work.

My problem is this:

* When using `npm run webpacker:prod` my asset files (a css file in this instance) build fine. I change a variable like `background-color` from `blue` to `pink`, run it using the above command, refresh the page and my background colour has changed from blue to pink. Great!
* When repeating the process, reversing now from `pink` to `blue` and running `npm run webpacker:dev`, when I refresh the page the colour hasn't changed. It's still pink!

Here is the output of the console when running the command, everything appears to work:

```
[seventy-two] npm run webpacker:dev

> @ webpacker:dev /Users/chrish/Development/72-tattoo/user/themes/seventy-two
> node webpack.config.js --mode=development


WEBPACKER => development mode

ℹ start building...
✔ compiling
⠙ building[Browsersync] Copy the following snippet into your website, just before the closing </body> tag
<script id="__bs_script__">//<![CDATA[
    document.write("<script async src='http://HOST:3001/browser-sync/browser-sync-client.js?v=2.26.3'><\/script>".replace("HOST", location.hostname));
//]]></script>

[Browsersync] Access URLs:
 ----------------------------------
          UI: http://localhost:3002
 ----------------------------------
 UI External: http://localhost:3002
 ----------------------------------
[Browsersync] Watching files...
✔ building
✔ finish module graph
✔ sealing
✔ basic dependencies optimization
✔ dependencies optimization
✔ advanced dependencies optimization
✔ after dependencies optimization
✔ chunk graph
✔ after chunk graph
✔ optimizing
✔ basic module optimization
✔ module optimization
✔ advanced module optimization
✔ after module optimization
✔ basic chunk optimization
✔ chunk optimization
✔ advanced chunk optimization
✔ after chunk optimization
✔ module and chunk tree optimization
✔ after module and chunk tree optimization
✔ basic chunk modules optimization
✔ chunk modules optimization
✔ advanced chunk modules optimization
✔ after chunk modules optimization
✔ module reviving
✔ module order optimization
✔ advanced module order optimization
✔ before module ids
✔ module ids
✔ module id optimization
✔ chunk reviving
✔ chunk order optimization
✔ before chunk ids
✔ chunk id optimization
✔ after chunk id optimization
✔ record modules
✔ record chunks
✔ hashing
✔ content hashing
✔ after hashing
✔ record hash
✔ module assets processing
✔ chunk assets processing
✔ additional chunk assets processing
✔ recording
✔ additional asset processing
✔ chunk asset optimization
✔ after chunk asset optimization
✔ asset optimization
✔ after asset optimization
✔ after seal
✔ emitting
✔ after emitting


 DONE  Compiled successfully in 2397ms     
```

If I change anything in the css file, it will automatically build _but_ the webpage doesn't reload. I'm running from `http://localhost:8000/` -- if i visit `http://localhost:3002` I get the BrowserSync page, if I visit `http://localhost:3001` I get a `Cannot get /` error, and if I visit `http://localhost:3000` I get 'Page cannot be reached'.

Am I doing something wrong here? Please ask if you need me to post anything else.

**Comment by n0k5** [comment]
@jimblue sent it over, cheers 👍

**Comment by n0k5** [comment]
Bit of further information for you.

Running `npm run webpacker:prod` gives me the following error:

```
(node:95843) UnhandledPromiseRejectionWarning: Error: Expected a `target`
    at module.exports (/Users/chrish/Development/72-tattoo/user/themes/seventy-two/node_modules/opn/index.js:8:25)
    at buildCallback (/Users/chrish/Development/72-tattoo/user/themes/seventy-two/node_modules/grav-plugin-webpacker/src/webpack/script/prod.j
s:38:31)
    at finalCallback (/Users/chrish/Development/72-tattoo/user/themes/seventy-two/node_modules/webpack/lib/Compiler.js:210:39)
    at hooks.done.callAsync.err (/Users/chrish/Development/72-tattoo/user/themes/seventy-two/node_modules/webpack/lib/Compiler.js:259:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/chrish/Development/72-tattoo/user/themes/seventy-two/node_modules/tapable/l
ib/HookCodeFactory.js:32:10), <anonymous>:51:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/chrish/Development/72-tattoo/user/themes/seventy-two/node_modules/tapable/lib/Hook.js:154:20)
    at emitRecords.err (/Users/chrish/Development/72-tattoo/user/themes/seventy-two/node_modules/webpack/lib/Compiler.js:257:22)
    at Compiler.emitRecords (/Users/chrish/Development/72-tattoo/user/themes/seventy-two/node_modules/webpack/lib/Compiler.js:371:39)
    at emitAssets.err (/Users/chrish/Development/72-tattoo/user/themes/seventy-two/node_modules/webpack/lib/Compiler.js:251:10)
    at hooks.afterEmit.callAsync.err (/Users/chrish/Development/72-tattoo/user/themes/seventy-two/node_modules/webpack/lib/Compiler.js:357:14)
    at _err2 (eval at create (/Users/chrish/Development/72-tattoo/user/themes/seventy-two/node_modules/tapable/lib/HookCodeFactory.js:32:10),
<anonymous>:36:1)
    at callback (/Users/chrish/Development/72-tattoo/user/themes/seventy-two/node_modules/stylelint-webpack-plugin/lib/run-compilation.js:57:5
)
    at _promise0.then._result0 (eval at create (/Users/chrish/Development/72-tattoo/user/themes/seventy-two/node_modules/tapable/lib/HookCodeF
actory.js:32:10), <anonymous>:32:1)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:95843) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async
function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:95843) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not h
andled will terminate the Node.js process with a non-zero exit code.
```

This can be fixed by changing `open_website`, `open_browsersyncui` and `open_bundleanalyzer` from `true` to `false`.

**Comment by jimblue** [comment]
Ok tks for the feedback, I'll make some test as soon as I can to keep you inform. Cheers

**Comment by n0k5** [comment]
Thanks, I'll see if I can figure anything out as well. At the moment I'm
manually running `npm run webpack:prod` every time I want to build and it's
pretty tedious.

**Comment by realcgslav** [comment]
I've the same problem as @n0k5. What I've found so far is that :dev is not watching changes in app.scss. Adding this in webpacker/src/webpack/output.js: `filename: GravConfig.dev ? ['js/[name].js' : 'js/[name].[chunkhash].js', 'css/[name].css' : 'css/[name].[chunkhash].css'],` triggers watch event but still app.***.css is not updated. 

I'm digging further.

**Comment by jimblue** [comment]
Thanks for the feedback guys, I'm pretty busy right now. Will have a look into this at the next year... It's not very far away form now! 😄 

Enjoy Christmas time! 🎄🎄 🎄 

Cheers

**Comment by realcgslav** [comment]
Hi @jimblue any progress with this issue?

**Comment by souricevincent** [comment]
`require('./../scss/app.scss')` in your file `src/js/app.js`

**Comment by Maybach91** [comment]
Any news on this?

**Comment by jimblue** [comment]
I'm concentrating on a huge refactor of the plugin which resolve this issue and others but also add many new nice features.
So I have no plan to make a quick fix sorry. (PR are welcome)

**Comment by Maybach91** [comment]
Sounds nice! What do you think when you will be able to make a release of the refactored one? :)

**Comment by jimblue** [comment]
no idea it's a huge work, doing it on my free time
