### ISSUE TITLE
Production mode not working

### ISSUE THREAD

**Issue by sandoche** [jimblue/grav-plugin-webpacker#5]
I managed to setup the dev mode. But when I run the prod mode I get the following error.

```
 DONE  Compiled successfully in 1940ms                                                                                   18:35:08

Built at: 20/06/2018 18:35:08
                              Asset       Size  Chunks             Chunk Names
js/manifest.834495ab7967b45e5edc.js   1.44 KiB       0  [emitted]  manifest
  js/script.81e57bd8fb6b19d2ee19.js  142 bytes       1  [emitted]  script
css/snitco.5f574c3749ee398aa6f3.css   9.44 KiB       2  [emitted]  snitco
  js/snitco.9c53e3211208a8cbcce1.js  132 bytes       2  [emitted]  snitco
                     webpacker.json  510 bytes          [emitted]  
(node:25355) UnhandledPromiseRejectionWarning: Error: Exited with code 4
    at ChildProcess.cp.once.code (/home/sandoche/Documents/Projects/IMT-SIT-website/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
(node:25355) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25355) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.



```

**Comment by sandoche** [comment]
I managed to fix it by changing these settings from true to false.
Only problem that I still have the css, and js files are not injected in the template in prod.
```
open_browsersyncui: false
open_bundleanalyzer: false
open_jarvis: false
```

**Comment by sandoche** [comment]
Actually when I check the source of my page rendered. I see the right files loaded but without the hash.

**Comment by sandoche** [comment]
I finally managed by just changing the setting to production.
